/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import PageControl from "./script/PageControl"
import Ground from "./script/Ground"
import Role from "./script/Role"
import Tail from "./script/Tail"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="scene/Scene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/PageControl.ts",PageControl);
        reg("script/Ground.ts",Ground);
        reg("script/Role.ts",Role);
        reg("script/Tail.ts",Tail);
    }
}
GameConfig.init();